### author: www.mrdoc.fun | jonnyan404
### 转载请保留来源
### update：2022年08月14日
version: '2.0'
services:
    ztncui:
        container_name: zt1
        restart: always
        environment:
            - HTTP_PORT=4000
            - HTTP_ALL_INTERFACES=yes
            - ZTNCUI_PASSWD=password
            - ZT_ADDR=localhost:5599
        ports:
            - '4000:4000' # web控制台入口
            - '5599:5599'
            - '5599:5599/udp'
            - '3180:3180' # planet/moon文件在线下载入口，如不对外提供。可防火墙禁用此端口。
        volumes:
            - './zerotier-one:/var/lib/zerotier-one'
            - './ztncui/etc:/opt/key-networks/ztncui/etc'
            # 按实际路径挂载卷， 冒号前面是宿主机的， 支持相对路径
        image: smallbutstrong/zerotier
